spring.application.name=WSPrestamos
server.port=8080
spring.data.mongodb.uri=mongodb+srv://andres:aquino@clustermontepiedad.yjuo06d.mongodb.net/?appName=ClusterMontePiedad
spring.data.mongodb.database=MontePiedad
token.service.url=https://wstoken-e4bbh5cqfcdrghe3.canadacentral-01.azurewebsites.net/api/token
