spring.application.name=WSPrestamos
server.port=8080
spring.data.mongodb.uri=mongodb+srv://andres:aquino@clustermontepiedad.yjuo06d.mongodb.net/?appName=ClusterMontePiedad
spring.data.mongodb.database=MontePiedad
token.service.url=http://localhost:8081/api/token
